AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rb
  Exclude:
    - Rakefile
    - bin/*
    - config.ru
    - config/**/*
    - vendor/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/TrivialAccessors:
  Enabled: true
  ExactNameMatch: true
  AllowPredicates: true

# TODO in the future try to reduce this section:
Metrics/AbcSize:
  Max: 36

Metrics/ClassLength:
  Max: 125

Metrics/ModuleLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

# "Prefer !expression.nil? over expression != nil." no way!
Style/NonNilCheck:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
