AllCops:
  Exclude:
    - bin/*
    - vendor/**/*
    - gems/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db_memoize.gemspec
    - tasks/*.rake

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# Try to keep those numbers low:

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/ModuleLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30
